<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        try { // try로 감싼 코드에서 에러가 나면 catch로 보내서 수습한다.
            //에러객체 생성가능
           let myError = new Error ("직접만든 에러입니다");
           //throw myError;//강제로 에러를 줘봤다.!!
        }   catch(e) { // 에러가 났을경우 어떻게 대처할지 코드를 작성
            console.log(e.message);
        }
        // try-catch문을 사용하면 아래 코드도 실행된다.
        document.write("예외가발생한 후 실행되는 코드입니다");
    </script>
</body>
</html>